"""added default role to users

Revision ID: 157fa1baf154
Revises: ca9de0bd4a34
Create Date: 2025-06-16 13:44:14.697286

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "157fa1baf154"
down_revision: Union[str, None] = "ca9de0bd4a34"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
