"""updated_the_stream_key_column_unique

Revision ID: 1c14f1db228e
Revises: 520b83490775
Create Date: 2025-05-04 17:51:55.723753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c14f1db228e'
down_revision: Union[str, None] = '520b83490775'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_stream_endpoints_stream_key', 'stream_endpoints', ['stream_key'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_stream_endpoints_stream_key', 'stream_endpoints', type_='unique')
    # ### end Alembic commands ###
