"""removed_returncode_from_bbbMeeting_table

Revision ID: 207be43efa8f
Revises: cba45cc14bf1
Create Date: 2025-05-06 14:18:16.738340

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "207be43efa8f"
down_revision: Union[str, None] = "cba45cc14bf1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bbb_meetings_return_code", table_name="bbb_meetings")
    op.drop_column("bbb_meetings", "return_code")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bbb_meetings",
        sa.Column("return_code", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.create_index(
        "ix_bbb_meetings_return_code", "bbb_meetings", ["return_code"], unique=False
    )
    # ### end Alembic commands ###
