"""update twitch token timezone

Revision ID: 29ac2a4a1aa4
Revises: 1076662609b1
Create Date: 2025-06-09 13:50:20.175954

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "29ac2a4a1aa4"
down_revision: Union[str, None] = "1076662609b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
