"""Fixed the cascade relationship between events and channels

Revision ID: 30831802b959
Revises: a4eb7a98409b
Create Date: 2025-05-27 06:14:11.804446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30831802b959'
down_revision: Union[str, None] = 'a4eb7a98409b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('events_channel_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_channel_id_fkey', 'events', 'channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###
