"""updated_name_of_channel_table_to_unique

Revision ID: 347ee19d9a7b
Revises: e159b1d36e0c
Create Date: 2025-05-13 02:14:28.208972

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "347ee19d9a7b"
down_revision: Union[str, None] = "e159b1d36e0c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "channels", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("channels_name_key", "channels", type_="unique")
    # ### end Alembic commands ###
