"""Fix created_at and updated_at columns and deleted the password column

Revision ID: 3b5514702f1a
Revises: a4a67fa33b4f
Create Date: 2025-04-30 15:15:02.407870

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3b5514702f1a"
down_revision: Union[str, None] = "a4a67fa33b4f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
