"""removed_organizer_column_from_event_table

Revision ID: 3d8c0c36f471
Revises: 764b45375472
Create Date: 2025-05-10 00:14:52.456263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d8c0c36f471'
down_revision: Union[str, None] = '764b45375472'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('events', 'organizer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('organizer', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
