"""pdated_ models_createat_updatedat_columns

Revision ID: 57185a948754
Revises: 1ec67573d580
Create Date: 2025-05-10 13:02:11.072747

"""

from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = "57185a948754"
down_revision: Union[str, None] = "1ec67573d580"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
