"""created_meetings_table

Revision ID: 631f63524ef9
Revises: 1c14f1db228e
Create Date: 2025-05-06 13:56:00.780957

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "631f63524ef9"
down_revision: Union[str, None] = "1c14f1db228e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bbb_meetings",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("return_code", sa.Boolean(), nullable=True),
        sa.Column("meeting_id", sa.String(), nullable=False),
        sa.Column("internal_meeting_id", sa.String(), nullable=False),
        sa.Column("parent_meeting_id", sa.String(), nullable=True),
        sa.Column("attendee_pw", sa.String(), nullable=False),
        sa.Column("moderator_pw", sa.String(), nullable=False),
        sa.Column("create_time", sa.String(), nullable=True),
        sa.Column("voice_bridge", sa.String(), nullable=True),
        sa.Column("dial_number", sa.String(), nullable=True),
        sa.Column("has_user_joined", sa.Boolean(), nullable=True),
        sa.Column("duuration", sa.String(), nullable=True),
        sa.Column("has_been_forcibly_ended", sa.Boolean(), nullable=True),
        sa.Column("message_key", sa.String(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bbb_meetings_attendee_pw"),
        "bbb_meetings",
        ["attendee_pw"],
        unique=True,
    )
    op.create_index(
        op.f("ix_bbb_meetings_create_time"),
        "bbb_meetings",
        ["create_time"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bbb_meetings_dial_number"),
        "bbb_meetings",
        ["dial_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bbb_meetings_duuration"), "bbb_meetings", ["duuration"], unique=False
    )
    op.create_index(op.f("ix_bbb_meetings_id"), "bbb_meetings", ["id"], unique=False)
    op.create_index(
        op.f("ix_bbb_meetings_internal_meeting_id"),
        "bbb_meetings",
        ["internal_meeting_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_bbb_meetings_meeting_id"), "bbb_meetings", ["meeting_id"], unique=True
    )
    op.create_index(
        op.f("ix_bbb_meetings_message"), "bbb_meetings", ["message"], unique=False
    )
    op.create_index(
        op.f("ix_bbb_meetings_message_key"),
        "bbb_meetings",
        ["message_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bbb_meetings_moderator_pw"),
        "bbb_meetings",
        ["moderator_pw"],
        unique=True,
    )
    op.create_index(
        op.f("ix_bbb_meetings_parent_meeting_id"),
        "bbb_meetings",
        ["parent_meeting_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bbb_meetings_return_code"),
        "bbb_meetings",
        ["return_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bbb_meetings_voice_bridge"),
        "bbb_meetings",
        ["voice_bridge"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bbb_meetings_voice_bridge"), table_name="bbb_meetings")
    op.drop_index(op.f("ix_bbb_meetings_return_code"), table_name="bbb_meetings")
    op.drop_index(op.f("ix_bbb_meetings_parent_meeting_id"), table_name="bbb_meetings")
    op.drop_index(op.f("ix_bbb_meetings_moderator_pw"), table_name="bbb_meetings")
    op.drop_index(op.f("ix_bbb_meetings_message_key"), table_name="bbb_meetings")
    op.drop_index(op.f("ix_bbb_meetings_message"), table_name="bbb_meetings")
    op.drop_index(op.f("ix_bbb_meetings_meeting_id"), table_name="bbb_meetings")
    op.drop_index(
        op.f("ix_bbb_meetings_internal_meeting_id"), table_name="bbb_meetings"
    )
    op.drop_index(op.f("ix_bbb_meetings_id"), table_name="bbb_meetings")
    op.drop_index(op.f("ix_bbb_meetings_duuration"), table_name="bbb_meetings")
    op.drop_index(op.f("ix_bbb_meetings_dial_number"), table_name="bbb_meetings")
    op.drop_index(op.f("ix_bbb_meetings_create_time"), table_name="bbb_meetings")
    op.drop_index(op.f("ix_bbb_meetings_attendee_pw"), table_name="bbb_meetings")
    op.drop_table("bbb_meetings")
    # ### end Alembic commands ###
