"""Add created_at and updated_at to BbbMeeting

Revision ID: 676044f9a641
Revises: 5ed5a218e585
Create Date: 2025-05-21 19:59:07.339755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676044f9a641'
down_revision: Union[str, None] = '5ed5a218e585'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bbb_meetings', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('bbb_meetings', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_constraint('events_channel_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'channels', ['channel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_channel_id_fkey', 'events', 'channels', ['channel_id'], ['id'], ondelete='CASCADE')
    op.drop_column('bbb_meetings', 'updated_at')
    op.drop_column('bbb_meetings', 'created_at')
    # ### end Alembic commands ###
