"""Updated_the_relationship_between_tables

Revision ID: 764b45375472
Revises: 510a08fd710d
Create Date: 2025-05-09 14:12:28.049843

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "764b45375472"
down_revision: Union[str, None] = "510a08fd710d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_event_association",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("event_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "event_id"),
    )
    op.add_column("channels", sa.Column("creator_id", sa.UUID(), nullable=False))
    op.drop_constraint("channels_user_id_fkey", "channels", type_="foreignkey")
    op.create_foreign_key(None, "channels", "users", ["creator_id"], ["id"])
    op.drop_column("channels", "user_id")
    op.add_column("events", sa.Column("creator_id", sa.UUID(), nullable=False))
    op.drop_constraint("events_user_id_fkey", "events", type_="foreignkey")
    op.create_foreign_key(None, "events", "users", ["creator_id"], ["id"])
    op.drop_column("events", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "events", type_="foreignkey")
    op.create_foreign_key("events_user_id_fkey", "events", "users", ["user_id"], ["id"])
    op.drop_column("events", "creator_id")
    op.add_column(
        "channels", sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False)
    )
    op.drop_constraint(None, "channels", type_="foreignkey")
    op.create_foreign_key(
        "channels_user_id_fkey", "channels", "users", ["user_id"], ["id"]
    )
    op.drop_column("channels", "creator_id")
    op.drop_table("user_event_association")
    # ### end Alembic commands ###
