"""Updated_attr_meeting_created

Revision ID: 88f952262c32
Revises: 9e981564fabc
Create Date: 2025-05-16 02:45:06.432247

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88f952262c32"
down_revision: Union[str, None] = "9e981564fabc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("meeting_created", sa.String(), nullable=False))
    op.drop_column("events", "meeting_started")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "events",
        sa.Column("meeting_started", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.drop_column("events", "meeting_created")
    # ### end Alembic commands ###
