"""updated_table_column_type

Revision ID: 89af1605cfd5
Revises: 207be43efa8f
Create Date: 2025-05-06 14:58:21.329785

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "89af1605cfd5"
down_revision: Union[str, None] = "207be43efa8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "bbb_meetings",
        "has_user_joined",
        existing_type=sa.BOOLEAN(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.alter_column(
        "bbb_meetings",
        "has_been_forcibly_ended",
        existing_type=sa.BOOLEAN(),
        type_=sa.String(),
        existing_nullable=True,
    )
    op.create_index(
        op.f("ix_bbb_meetings_has_been_forcibly_ended"),
        "bbb_meetings",
        ["has_been_forcibly_ended"],
        unique=False,
    )
    op.create_index(
        op.f("ix_bbb_meetings_has_user_joined"),
        "bbb_meetings",
        ["has_user_joined"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bbb_meetings_has_user_joined"), table_name="bbb_meetings")
    op.drop_index(
        op.f("ix_bbb_meetings_has_been_forcibly_ended"), table_name="bbb_meetings"
    )
    op.alter_column(
        "bbb_meetings",
        "has_been_forcibly_ended",
        existing_type=sa.String(),
        type_=sa.BOOLEAN(),
        existing_nullable=True,
    )
    op.alter_column(
        "bbb_meetings",
        "has_user_joined",
        existing_type=sa.String(),
        type_=sa.BOOLEAN(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
