"""updated_title_of_event_table_to_unique

Revision ID: 9a184008a7ba
Revises: 347ee19d9a7b
Create Date: 2025-05-16 01:11:48.768385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a184008a7ba'
down_revision: Union[str, None] = '347ee19d9a7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'events', ['title'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("events_title_key", 'events', type_='unique')
    # ### end Alembic commands ###
