"""Added_attr-related-to-bbb-meeting

Revision ID: 9e981564fabc
Revises: 9a184008a7ba
Create Date: 2025-05-16 02:30:29.695719

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9e981564fabc"
down_revision: Union[str, None] = "9a184008a7ba"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("meeting_id", sa.String(), nullable=True))
    op.add_column("events", sa.Column("moderator_pw", sa.String(), nullable=True))
    op.add_column("events", sa.Column("attendee_pw", sa.String(), nullable=True))
    op.add_column("events", sa.Column("meeting_started", sa.String(), nullable=False))
    op.create_unique_constraint("uq_events_moderator_pw", "events", ["moderator_pw"])
    op.create_unique_constraint("uq_events_meeting_id", "events", ["meeting_id"])
    op.create_unique_constraint("uq_events_attendee_pw", "events", ["attendee_pw"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_events_attendee_pw", "events", type_="unique")
    op.drop_constraint("uq_events_meeting_id", "events", type_="unique")
    op.drop_constraint("uq_events_moderator_pw", "events", type_="unique")
    op.drop_column("events", "meeting_started")
    op.drop_column("events", "attendee_pw")
    op.drop_column("events", "moderator_pw")
    op.drop_column("events", "meeting_id")
    # ### end Alembic commands ###
