"""fixed_bbbMeeting_table_attribute

Revision ID: cba45cc14bf1
Revises: 631f63524ef9
Create Date: 2025-05-06 13:57:36.531940

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cba45cc14bf1"
down_revision: Union[str, None] = "631f63524ef9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bbb_meetings", sa.Column("duration", sa.String(), nullable=True))
    op.drop_index("ix_bbb_meetings_duuration", table_name="bbb_meetings")
    op.create_index(
        op.f("ix_bbb_meetings_duration"), "bbb_meetings", ["duration"], unique=False
    )
    op.drop_column("bbb_meetings", "duuration")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "bbb_meetings",
        sa.Column("duuration", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_index(op.f("ix_bbb_meetings_duration"), table_name="bbb_meetings")
    op.create_index(
        "ix_bbb_meetings_duuration", "bbb_meetings", ["duuration"], unique=False
    )
    op.drop_column("bbb_meetings", "duration")
    # ### end Alembic commands ###
