"""update_bbbMeeting-table-

Revision ID: dd2eaf2c0bcd
Revises: 89af1605cfd5
Create Date: 2025-05-07 01:35:56.443200

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "dd2eaf2c0bcd"
down_revision: Union[str, None] = "89af1605cfd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_bbb_meetings_attendee_pw", table_name="bbb_meetings")
    op.create_index(
        op.f("ix_bbb_meetings_attendee_pw"),
        "bbb_meetings",
        ["attendee_pw"],
        unique=False,
    )
    op.drop_index("ix_bbb_meetings_moderator_pw", table_name="bbb_meetings")
    op.create_index(
        op.f("ix_bbb_meetings_moderator_pw"),
        "bbb_meetings",
        ["moderator_pw"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_bbb_meetings_moderator_pw"), table_name="bbb_meetings")
    op.create_index(
        "ix_bbb_meetings_moderator_pw", "bbb_meetings", ["moderator_pw"], unique=True
    )
    op.drop_index(op.f("ix_bbb_meetings_attendee_pw"), table_name="bbb_meetings")
    op.create_index(
        "ix_bbb_meetings_attendee_pw", "bbb_meetings", ["attendee_pw"], unique=True
    )
    # ### end Alembic commands ###
