"""add_cascade_delete_to_user_event_association

Revision ID: e159b1d36e0c
Revises: 8d2a64ea4d0f
Create Date: 2025-05-12 12:00:10.914931

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e159b1d36e0c"
down_revision: Union[str, None] = "8d2a64ea4d0f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "user_event_association_event_id_fkey",
        "user_event_association",
        type_="foreignkey",
    )
    op.drop_constraint(
        "user_event_association_user_id_fkey",
        "user_event_association",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None, "user_event_association", "users", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        None,
        "user_event_association",
        "events",
        ["event_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user_event_association", type_="foreignkey")
    op.drop_constraint(None, "user_event_association", type_="foreignkey")
    op.create_foreign_key(
        "user_event_association_user_id_fkey",
        "user_event_association",
        "users",
        ["user_id"],
        ["id"],
    )
    op.create_foreign_key(
        "user_event_association_event_id_fkey",
        "user_event_association",
        "events",
        ["event_id"],
        ["id"],
    )
    # ### end Alembic commands ###
