"""Added userId to twitch token table

Revision ID: fb4e0e1c0e69
Revises: 157fa1baf154
Create Date: 2025-06-16 20:28:33.350187

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fb4e0e1c0e69"
down_revision: Union[str, None] = "157fa1baf154"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("twitch_tokens", sa.Column("user_id", sa.UUID(), nullable=False))
    op.create_index(
        op.f("ix_twitch_tokens_user_id"), "twitch_tokens", ["user_id"], unique=False
    )
    op.create_foreign_key(
        "fk_twitch_tokens_user_id", "twitch_tokens", "users", ["user_id"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_twitch_tokens_user_id", "twitch_tokens", type_="foreignkey")
    op.drop_index(op.f("ix_twitch_tokens_user_id"), table_name="twitch_tokens")
    op.drop_column("twitch_tokens", "user_id")
    # ### end Alembic commands ###
